name:                earley-parser
version:             0.1.0.0
author:              "Emily Wang"
maintainer:          "sw50@illinois.edu"

extra-source-files:
- README.md

description:         Please refer to the README

dependencies:
- base
- unordered-containers

library:
    source-dirs: src

executables:
    earley-parser:
        main: Main.hs
        source-dirs: app
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - earley-parser

tests:
    spec:
        main:                Spec.hs
        source-dirs:         test
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            - -main-is Spec.main
        dependencies:
            - earley-parser
            - HTF
